packages:
  - packages/*
ignoredBuiltDependencies:
  - esbuild
  - '@unit-mesh/treesitter-artifacts'
onlyBuiltDependencies:
  - '@vscode/ripgrep'
  - nodejieba
  - onnxruntime-node
  - protobufjs
  - sharp
  - sqlite3
  - vscode-ripgrep
publishBranch: "main|master|gitbutler/workspace"
nodeLinker: "hoisted"