name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Core Build
        run: pnpm --filter worker-core build

      - name: Web Build
        run: pnpm --filter web build

      - name: Run Core Tests
        run: pnpm --filter worker-core vitest run

      - name: Run Web Tests
        run: pnpm --filter web vitest run

      - name: Run MCP Tests
        run: pnpm --filter context-mcp vitest run
